name: Release

on:
    push:
      branches:
        - main

permissions:
    contents: write
    pull-requests: write

jobs:
    auto-merge:
        uses: edpft/rust-workflows/.github/workflows/release-please.yml@main
        with:
            package-name: "PACKAGE_NAME"